name: release

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  build_all:
    uses: ./.github/workflows/build.yaml
  release:
    runs-on: ubuntu-latest
    needs: build_all
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl ${{ needs.build_all.outputs.linux }} -o linux.zip
          curl ${{ needs.build_all.outputs.windows }} -o windows.zip
          unzip linux
          unzip windows
          ls
      # - uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       ./tar*
      #       SHA256.txt
